server:
    port: 8761
    error:
        whitelabel:
            enabled: false
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka


spring:
  cloud:
    gateway:
      routes:
      - id: insurer-profile-post
        uri: http://158.69.36.44:8081/api/insurercontroller/insurer/profile/post/1.0
        predicates:
        - Path=/api/insurercontroller/insurer/profile/post/**
      - id: insurer-profile-get
        uri: http://158.69.36.44:8081/api/insurercontroller/insurer/profile/get/1.0?pageSize=10
        predicates:
        - Path=/api/insurercontroller/insurer/profile/get/**
      - id: eureka-api-gateway
        uri: http://127.0.0.1:8761/eureka
        predicates:
        - Path=/eureka/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: TRACE
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

    

